### ISSUE TITLE
Use system Gtk Theme

### ISSUE THREAD

**Issue by janopae** [Philip-Scott/Notes-up#368] opened 2020-12-05 14:08 UTC
Hi! First of all, I think Notes-Up is a great idea of an application - there is actually the need for a simple and beautiful notes app that supports markdown. Thank you for making it!

## Expected Behavior
I was even more hyped about it when I saw it used Gtk and Vala, because I thought this made if fit greatly into the look & feel provided by Ubuntu. When installing a Flatpak in Ubuntu, and it is a Gtk application, they usually use Ubuntu's built in Yaru theme. This is because the `org.gtk.Gtk3theme.Yaru` Flatpak is installed. 

## Current Behavior
However, Notes-up uses the same theme like on the README/website/AppStream screenshots, which is what I believe to be the ElementaryOS theme. It doesn't look bad or something, it just doesn't fit at all to the design language of Ubuntu - which I think is a pity, as it is a Gtk application, and the technical hurdle of using the system Gtk theme shouldn't be that big. There is even a Gtk theme for KDE's breeze theme (which is very good and feels very native), so it could nicely integrate into the Plasma desktop as well if it only used the system Gtk theme.

## Possible Solution
On the Internet, I found screenshots of earlier versions of Notes up that appear to use the system Gtk theme. Were there any issues with that? Could this behaviour be restored?

## Steps to Reproduce (for bugs)

1. Install Notes-up
2. Launch it, having a different system-wide theme than the ElementaryOS one
3. See how Notes-up still uses what seems to be the ElementaryOS theme

## Screenshots of the Problem

![Bildschirmfoto von 2020-12-05 15-06-40](https://user-images.githubusercontent.com/8160319/101245240-a6f25780-370b-11eb-9f5e-8d2de8c3d02e.png)

**Comment by Philip-Scott** [comment] 2020-12-09 21:49
Hey Janopae, 

The Flatpak version of the app is actually made to run with the elementary theme by design. This is mostly since the app was built with that theme in mind, and it is just what the app supports officially. If you instead build the app manually, that installation will use you system's them as I don't have control over that. I'm going to be closing the issue and marking it as "by design" :)

**Closed by Philip-Scott** 2020-12-09 21:49 UTC

**Comment by janopae** [comment] 2020-12-16 17:28
@Philip-Scott Ok thanks, good to know. Just because I'm curious: Are you in general open for someone else maintaining support for integrating with other themes, or is this project opinionated in this regard?
