### ISSUE TITLE
Feature Suggestion: Drag N' Rearrange

### ISSUE THREAD

**Issue by proxycyber** [Philip-Scott/Notes-up#162] opened 2017-08-02 22:03 UTC
In the List View, it'd be cool if we could freely drag items above or below each other, say for example custom order list view.

**Comment by Philip-Scott** [comment] 2017-08-04 16:35
duplicate of #23 

Sadly, it's a bit harder to do since the ListBox doesn't really support Drag N Drop :/

**Closed by Philip-Scott** 2017-08-04 16:35 UTC
