### ISSUE TITLE
Drag'n'Drop

### ISSUE THREAD

**Issue by sgpthomas** [Philip-Scott/Notes-up#114] opened 2017-04-30 17:20 UTC
Would be cool to be able to drag notes from one notebook into another notebook. You would drag it from the middle sidebar to the right notebook sidebar. Maybe even allow dragging to trash for deletion?

**Comment by Philip-Scott** [comment] 2017-04-30 22:57
Yes! I would actually love to get that working (It's actually been on the pipeline since #23....) But sadly, i haven't been able to get Drag n Drop working on the sidebar and on the pages list :/ I might 

(Closing this since is a duplicate of that report)

**Closed by Philip-Scott** 2017-04-30 22:57 UTC
