### ISSUE TITLE
Feature Request: Standard Notes Integration

### ISSUE THREAD

**Issue by Hedronmx** [Philip-Scott/Notes-up#140] opened 2017-07-06 00:42 UTC
Your app is amazing and it would be totally killer if you added Standard Notes integration. The ui of your app is very similar to Standar's and it would be really nice if we could sync the note to the cloud.

Thanks for your great work!!

**Comment by Philip-Scott** [comment] 2017-07-19 15:55
duplicate of #70. The problem with online syncing is that there is no one service everyone uses.... I just leave it up to the user to use the platform of your choice to backup your DB file

**Closed by Philip-Scott** 2017-07-19 15:55 UTC
Labels: duplicate
