### ISSUE TITLE
[feature request] WikiWord support

### ISSUE THREAD

**Issue by jalberto** [Philip-Scott/Notes-up#275] opened 2018-05-08 10:47 UTC
Will be great to have the ability to link to other notes automatically, ideally using WikiWord syntax

- WikiWord should link to "WikiWord` note name
- if note doesn't exist, create it on click

**Comment by Philip-Scott** [comment] 2018-05-08 12:37
Closing since it's a duplicate of #107 ;)

**Closed by Philip-Scott** 2018-05-08 12:37 UTC
