### ISSUE TITLE
Bug: application sometimes crashes when double clicking the name of the note to exit edit mode

### ISSUE THREAD

**Issue by ChristopherNugent** [Philip-Scott/Notes-up#294] opened 2018-09-14 00:50 UTC
Terminal output
```
[INFO 20:10:04.593570] Application.vala:154: Notes-Up version: 1.3
[INFO 20:10:04.593609] Application.vala:156: Kernel version: 4.15.0-33-generic
[WARNING 20:10:04.608686] Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-C91BgcGKuO: Connection refused

** (WebKitWebProcess:12005): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-C91BgcGKuO: Connection refused
[FATAL 20:10:58.660716] enchant_dict_check: assertion 'len' failed
[FATAL 20:11:03.125433] enchant_dict_check: assertion 'len' failed
[FATAL 20:12:12.657655] enchant_dict_check: assertion 'len' failed
[FATAL 20:12:15.127662] enchant_dict_check: assertion 'len' failed
[FATAL 20:12:26.159448] enchant_dict_check: assertion 'len' failed
[FATAL 20:12:26.463350] enchant_dict_check: assertion 'len' failed
[FATAL 20:12:27.325258] enchant_dict_check: assertion 'len' failed
[FATAL 20:12:28.335833] enchant_dict_check: assertion 'len' failed
[FATAL 20:12:29.896170] enchant_dict_check: assertion 'len' failed
[FATAL 20:12:30.177992] enchant_dict_check: assertion 'len' failed
[FATAL 20:12:30.363993] enchant_dict_check: assertion 'len' failed
[FATAL 20:14:52.965461] [GLib-GIO] g_file_get_basename: assertion 'G_IS_FILE (file)' failed
[FATAL 20:14:52.965536] [GLib] g_utf8_strdown: assertion 'str != NULL' failed
[FATAL 20:14:52.965587] [GLib] g_str_has_suffix: assertion 'str != NULL' failed
[FATAL 20:14:52.965652] [GLib-GIO] g_file_get_path: assertion 'G_IS_FILE (file)' failed
[FATAL 20:14:52.965685] [GLib-GIO] g_file_new_for_path: assertion 'path != NULL' failed
[FATAL 10:17:32.844025] enchant_dict_check: assertion 'len' failed
[FATAL 10:17:33.142112] enchant_dict_check: assertion 'len' failed
[FATAL 10:18:21.048981] enchant_dict_check: assertion 'len' failed
[FATAL 10:18:21.312793] enchant_dict_check: assertion 'len' failed
Segmentation fault (core dumped)
```
The application was installed from AppCenter

**Comment by ChristopherNugent** [comment] 2018-09-16 22:12
Sadly, I haven't noticed any specific thing that triggers it. It tends to happen when I switch between modes by double clicking the note to change modes, especially multiple times in the same session. I haven't found that it destroys any changes, so its an inconvenience more than anything else. 

If it is helpful for debugging, it does not save which note is currently being viewed, so it will re-open to a different note.

**Comment by Philip-Scott** [comment] 2018-09-18 12:29
There's a new release coming soon to AppCenter, maybe I've already fixed it indirectly :) Let's wait for the new release and see if it's still reproducible

**Comment by Philip-Scott** [comment] 2018-09-20 17:42
Closing for now as it's a duplicate of #280

**Closed by Philip-Scott** 2018-09-20 17:42 UTC
Labels: duplicate, needs info
