### ISSUE TITLE
Feature proposal: IMAP sync

### ISSUE THREAD

**Issue by mikeanthonywild** [Philip-Scott/Notes-up#126] opened 2017-05-17 20:23 UTC
Currently I'm able to sync my email, contacts, reminders, calendars and notes across all my devices without using any proprietary services / applications. The missing piece is accessing notes on elementary. 

I understand this leverages markdown quite heavily (I'm not sure how formatting in IMAP-based notes is achieved - I'd guess some limited subset of HTML like regular email?), so I'm not sure if this would fit in.

Just a thought though

**Comment by Philip-Scott** [comment] 2017-08-04 17:37
duplicate of #70, but it probably won't be IMAP, sorry

**Closed by Philip-Scott** 2017-08-04 17:37 UTC
