### ISSUE TITLE
printing markdown

### ISSUE THREAD

**Issue by psylock** [Philip-Scott/Notes-up#152] opened 2017-07-25 18:43 UTC
for now, i can't print any note. ctrl + P doesn't work. i can't print the pdf version, since the pdf export is empty.

**Comment by Philip-Scott** [comment] 2017-07-25 19:10
I'm guessing your computer is not in English ;) 

To get this to work on your language, i need your help :) Can you follow what this says, and send me a screenshot of your print dialog? Thanks!

https://github.com/Philip-Scott/Notes-up/issues/1#issuecomment-313936098

**Comment by kostrykin** [comment] 2017-07-25 19:13
Export as PDF doesn't work for me either, the PDF is just of 0 byte in size. In that case, you also need that screenshot? I haven't tried printing and my system localization is German.

**Comment by Philip-Scott** [comment] 2017-07-25 19:44
@kostrykin Yes please :) 

But the printing you can get it from any other app, preferably try printing an image

**Comment by kostrykin** [comment] 2017-07-26 09:05
Hope this helps.

![print](https://user-images.githubusercontent.com/6557139/28613313-5c591808-71f2-11e7-9cbf-2534f6f12dc5.png)

**Comment by psylock** [comment] 2017-07-26 13:50
![capture d ecran de 2017-07-26 15-47-31](https://user-images.githubusercontent.com/21148874/28624650-0efe9bc8-721a-11e7-8e37-3bc53fbcc347.png)
This one ?

**Comment by Philip-Scott** [comment] 2017-07-26 16:27
@psylock What language are you using? :)

@kostrykin It's been fixed in master, you'll get the update soon in AppCenter :)

**Comment by psylock** [comment] 2017-07-26 16:35
@Philip-Scott fr_fr :)

**Comment by Philip-Scott** [comment] 2017-07-26 16:41
@psylock If you want to fix it yourself, you should do what this other guy did here, but to the fr.po file: https://github.com/Philip-Scott/Notes-up/pull/155

If not i'll just do it during the week, but if you could do it and test it yourself that would be awesome and a lot of help!

**Comment by psylock** [comment] 2017-07-26 17:13
unfortunately, my make command block on Notes Up since a few weeks : 
`make[2]: ***  Aucune règle pour fabriquer la cible « libmarkdown.a », nécessaire pour « notes-up ». Arrêt.`
do you see how to fix that ?

**Comment by Philip-Scott** [comment] 2017-07-26 20:59
Fixed on the languages mentioned here. But closing since it's a duplicate of #1. Thank your for everyone's help!

**Closed by Philip-Scott** 2017-07-26 20:59 UTC
Labels: duplicate, help wanted
