### ISSUE TITLE
Empty PDF file sometimes get's created

### ISSUE THREAD

**Issue by igomezal** [Philip-Scott/Notes-up#1] opened 2016-02-29 20:51 UTC
Hello, when i try to export the markdown file to pdf it only creates a file of zero bytes 
![captura de pantalla de 2016-02-29 21 51 13](https://cloud.githubusercontent.com/assets/15131479/13408640/2e6a155c-df2f-11e5-917f-20af46fd2980.png)

**Comment by Philip-Scott** [comment] 2016-02-29 21:13
How does it happen? :) Are you trying to generate it straight from the editor?

**Comment by Philip-Scott** [comment] 2016-02-29 22:06
@igomezal Or can you confirm it happening?

**Comment by igomezal** [comment] 2016-03-01 00:21
No matter the windows you I use it always generates a file of 0 bytes.

Thanks for your hard work.

**Comment by Philip-Scott** [comment] 2016-03-01 00:25
@igomezal If you try to open the app from the terminal, and try to export to pdf, does the terminal output any error messages?

**Comment by igomezal** [comment] 2016-03-01 09:05
When I open notes-up this is what it prints in my terminal:
`ivan@ivan-Notebook:~$ notes-up`

`(Notes:3290):` Gtk-CRITICAL **: gtk_window_set_focus: assertion 'gtk_widget_get_can_focus (focus)' failed`

But when i press in export to pdf it doesn't print anything.

**Comment by Philip-Scott** [comment] 2016-03-01 11:45
From a web browser, try to print a website. But at the print dialog, sellect "print to file" or "to pdf" pr somethjng along the lines.

Does that work?

**Comment by Philip-Scott** [comment] 2016-03-01 11:51
How it works on my app is that I first create an empty file, and then I send that to the system's printer as if that was the printing location. 

What os, version, and that do you have?

**Comment by igomezal** [comment] 2016-03-01 16:04
I have just tried it and from the browser it works fine.
And I am using elementary OS 0.3.2 Freya 32-bit.

**Comment by Philip-Scott** [comment] 2016-05-12 22:52
I'm re-opening this due to it's original bug. I got another bug report about it

**Comment by psylock** [comment] 2016-09-04 20:01
I think it's due to FileManager.vala, l110 : 
    write_file (file, "");

the second argument is content, so with an empty string, the pdf is empty, isn't it ?

**Comment by Philip-Scott** [comment] 2016-09-04 20:06
@psylock The write_file (file, "") is just to make an empty file Webkit's printer is going to use... But you just made me think of something! The problem is that it's taking a bit longer to make the file and to load the page's contest so by the time it get's to the bottom it still isn't loaded. 

Can you reproduce the problem consistently?

**Comment by psylock** [comment] 2016-09-04 20:16
Every time i export for pdf, i got a 0 bite file. 

in write_file, you declare contents argument as a string, but after you call for a contents method (contents.data). I am misunderstanding ?

**Comment by Philip-Scott** [comment] 2016-09-04 20:40
@psylock Can you try out this patch? :smile: https://github.com/Philip-Scott/Notes-up/tree/pdf-print-test

**Comment by psylock** [comment] 2016-09-04 20:51
same result :'(

**Comment by Philip-Scott** [comment] 2016-09-04 21:20
Can you try it again? I got rid of that create empty file thing

**Comment by psylock** [comment] 2016-09-05 06:58
Still 0 bytes. Still "Printing..". message also.

**Comment by JO0st** [comment] 2017-02-09 09:53
To me it is still happining in version 1.3

**Comment by alx901** [comment] 2017-05-20 07:43
Install Notes-up 1.3 from Loki 0.4.1 from AppCenter.
Not worked export to PDF.  Created file in Zerro byte size.
Please fix this very important functions.

**Comment by marcos-90** [comment] 2017-07-09 04:51
I'm having the same issue. Always getting the 0 bytes file when exporting to PDF.

**Comment by Philip-Scott** [comment] 2017-07-09 04:54
@marcos-90 Please tell me more about your system. Such as what language are you using :)

Also, can you run `apt-cache policy libwebkit2gtk-4.0-dev` and `apt-cache policy libwebkit2gtk-3.0-25` and post here the full output? Thanks

**Comment by Philip-Scott** [comment] 2017-07-09 04:56
@marcos-90 sorry, `apt-cache policy libwebkit2gtk-4.0-37` as well :)

**Comment by marcos-90** [comment] 2017-07-09 05:12
Ok! (that was fast!! :) )

I'm using elementary os, 0.4.1, Loki in Spanish (Latin America). The only difference is that I installed the latest stable kernel in the ubuntu repos. I'm using kernel 4.11.2-041102-generic. I didn't change the repos or anything like that, i downloaded the kernel packages and installed them.

I installed the app using the software center.


libwebkit2gtk-4.0-dev:
  Instalados: (ninguno)
  Candidato:  2.16.3-0ubuntu0.16.04.1
  Tabla de versión:
     2.16.3-0ubuntu0.16.04.1 500
        500 http://ar.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
     2.10.9-1ubuntu1 500
        500 http://ar.archive.ubuntu.com/ubuntu xenial/main amd64 Packages

libwebkit2gtk-3.0-25:
  Instalados: (ninguno)
  Candidato:  2.4.11-0ubuntu0.1
  Tabla de versión:
     2.4.11-0ubuntu0.1 500
        500 http://ar.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
     2.4.10-0ubuntu1 500
        500 http://ar.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages

libwebkit2gtk-4.0-37:
  Instalados: 2.16.3-0ubuntu0.16.04.1
  Candidato:  2.16.3-0ubuntu0.16.04.1
  Tabla de versión:
 *** 2.16.3-0ubuntu0.16.04.1 500
        500 http://ar.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2.10.9-1ubuntu1 500
        500 http://ar.archive.ubuntu.com/ubuntu xenial/main amd64 Packages

**Comment by Philip-Scott** [comment] 2017-07-09 17:04
Hey! There we go! :D I'm finally able to reproduce it! Looks like non-English languages break "printing" on the app

**Comment by Philip-Scott** [comment] 2017-07-09 18:14
@everyone I was able to get it fixed in Spanish. Sadly, this requires translating a line of text 

https://github.com/Philip-Scott/Notes-up/commit/000b3581b7deb8296dec734639707478e232698a#diff-9427b2497682f9189e9ffae2687f88bfR42

If anyone can help doing the translations of this line like on the link above, you'll be able to fix it for everyone on your language! 

You can get the correct text for your language on the printing dialog like so: 
![captura realizada el 2017-07-09 13 14 15](https://user-images.githubusercontent.com/10786508/27996490-87538e14-64a8-11e7-9dd7-8f9d21f99422.png)

**Comment by marcos-90** [comment] 2017-07-10 13:42
For me i'ts working perfectly now! Great work! :D

I don't know much about coding, but I'll try to help with the things I can.

**Comment by Philip-Scott** [comment] 2017-10-20 15:43
I'm closing this since the fix is out.

**Closed by Philip-Scott** 2017-10-20 15:43 UTC
Labels: Confirmed, help wanted, Status In Progress

**Comment by hanaral** [comment] 2021-05-22 11:38
@Philip-Scott would it not be possible to have the string inherit whatever it's translated as in the webkit repo?
