### ISSUE TITLE
Export to pdf does not seem to work

### ISSUE THREAD

**Issue by rasmus91** [Philip-Scott/Notes-up#279] opened 2018-06-10 08:35 UTC
When i click the cog and choose export to pdf, i can make a file with a .pdf extension, but documentreader will not open the file.If i open it with a text editor, it just looks like an empty file.

**Comment by Philip-Scott** [comment] 2018-06-14 17:31
Duplicate of #1 , you probably use the app in a different language, but you can fix it for you and everyone by looking at the instructions in that other issue

**Closed by Philip-Scott** 2018-06-14 17:31 UTC
