### ISSUE TITLE
When deleting notes, I have to restart the app for the note to disappear from the list.

### ISSUE THREAD

**Issue by yerbestpal** [Philip-Scott/Notes-up#116] opened 2017-05-03 18:56 UTC
Even though there is visual confirmation of deletion via the trash section, the note remains listed and it can cause confusion unless I restart the app.

**Comment by Philip-Scott** [comment] 2017-05-10 03:33
It was actually by design to not hide the notes (Although they can't be edited once they're in the trash) But yeah, i think it does make more sense to just remove it from the list as well

**Comment by Philip-Scott** [comment] 2018-12-04 15:16
Closing, i've made it so they're insensitive now in the list :)

**Closed by Philip-Scott** 2018-12-04 15:16 UTC
Labels: UX
