### ISSUE TITLE
Enlarging minimum window width

### ISSUE THREAD

**Issue by fbruetting** [Philip-Scott/Notes-up#213] opened 2017-11-11 02:22 UTC
Is needed, because the current setting doesn’t make any sense and this also prevents tiling.

**Comment by Philip-Scott** [comment] 2017-11-11 02:26
Can you be more specific with what the problem is? I don't see a problem with having the window be as small as you need it. Then, i'd just be setting an arbitrary min size :) 

![image](https://user-images.githubusercontent.com/10786508/32685364-1f54ce22-c655-11e7-8639-43d6aedac5a6.png)

**Comment by fbruetting** [comment] 2017-11-11 02:33
Oh, it’s in Linux. I cannot make the window smaller in horizontal size, than the top icon bar in edit mode allows (this also applys in view mode).

**Comment by Philip-Scott** [comment] 2017-11-11 02:44
Well yeah, that's to be expected. If you could then elements could start being unavailable.

Can you post a screenshot of your current setup? maybe either your Gtk or icon theme are making things bigger than they're supposed to be. The min size gets pretty small (about 200px across)

**Comment by fbruetting** [comment] 2017-11-11 02:50
You’re right – it’s Adapta’s padding. Do you see some solution here, or should I contact the Adapta project?

**Comment by Philip-Scott** [comment] 2017-11-11 02:53
Try contacting them, it's not something that can be fixes from here :) 

You might also be able to start the app with another theme using env variables.

Closing and marking as "wont fix" since it's not an issue with Notes-Up. But thank you for filing issues

**Closed by Philip-Scott** 2017-11-11 02:53 UTC
Labels: needs info

**Comment by fbruetting** [comment] 2017-11-11 02:56
+tista500, what do you think?

**Comment by tista500** [comment] 2017-11-11 03:30
We do not support any ElementaryOS related platform and/or applications.

**Comment by Philip-Scott** [comment] 2017-11-11 03:39
@tista500 I am not doing anything "elementary only" with those icons thought. Could it be that there's just too much padding on them?

**Comment by tista500** [comment] 2017-11-11 03:56
Your app has `libgranite` build dependency. That's 'elementary-related' thing.

**Comment by tista500** [comment] 2017-11-11 03:59
Related to this widget? : https://github.com/Philip-Scott/Notes-up/blob/master/src/Widgets/ToolbarButton.vala

**Comment by Philip-Scott** [comment] 2017-11-11 04:03
Yes, it's related to that. It used the .flat class which shouldn't contain any padding :) (and it's also a SMALL_TOOLBAR icon

**Comment by tista500** [comment] 2017-11-11 04:07
So, how your app handles `.image-button' and `.text-button` style-class via `int type`?

**Comment by Philip-Scott** [comment] 2017-11-11 04:11
Type is used for behavior purposes, not style :)

**Comment by Philip-Scott** [comment] 2017-11-11 04:11
It might be that I need to add a style class to the container of the buttons

**Comment by tista500** [comment] 2017-11-11 04:15
> It might be that I need to add a style class to the container of the buttons

I'm not sure whether you should do or not, but we, Adwaita, and some other Gtk+ themes have some different types of padding and margins for each `.image-button`, `.text-button` and `.text-button.image-button` in GtkToolBar and/or at-root.

Adapta has `toolbar button.image-button` node: ($icon_size = 16px)
 min-width: $icon_size;
 min-height: $icon_size;
 padding: rem(6.7px);
